-- Plugins
vim.pack.add({ "https://gitlab.com/motaz-shokry/gruvbox.nvim" })
vim.pack.add({ "https://github.com/neovim/nvim-lspconfig" })
vim.pack.add({ "https://github.com/mason-org/mason.nvim" })
vim.pack.add({ "https://github.com/mason-org/mason-lspconfig.nvim" })
vim.pack.add({ "https://github.com/folke/lazydev.nvim" })
vim.pack.add({ "https://github.com/rafamadriz/friendly-snippets" })
vim.pack.add({ { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("1.*") } })
vim.pack.add({ "https://github.com/stevearc/conform.nvim" })
vim.pack.add({ "https://github.com/lewis6991/gitsigns.nvim" })
vim.pack.add({ "https://github.com/nvim-mini/mini.ai" })
vim.pack.add({ "https://github.com/nvim-mini/mini.surround" })
vim.pack.add({ "https://github.com/nvim-mini/mini.pairs" })
vim.pack.add({ "https://github.com/nvim-treesitter/nvim-treesitter" })
vim.pack.add({ "https://github.com/stevearc/oil.nvim" })
vim.pack.add({ "https://github.com/nvim-tree/nvim-web-devicons" })
vim.pack.add({ "https://github.com/MeanderingProgrammer/render-markdown.nvim" })
vim.pack.add({ "https://github.com/tpope/vim-fugitive" })
vim.pack.add({ "https://github.com/folke/snacks.nvim" })
vim.pack.add({ "https://github.com/catgoose/nvim-colorizer.lua" })
vim.pack.add({ "https://github.com/folke/which-key.nvim" })

require("config.options")
require("config.keymap")
require("config.autocmd")
