return {}
-- return {
-- 	"sphamba/smear-cursor.nvim",
-- 	config = function()
-- 		require("smear_cursor").setup({
-- 			cursor_color = "#ffffff",
-- 			gradient_exponent = 0,
-- 			particles_enabled = true,
-- 			particle_spread = 1,
-- 			particles_per_second = 100,
-- 			particles_per_length = 50,
-- 			particle_max_lifetime = 1500,
-- 			particle_max_initial_velocity = 10,
-- 			particle_velocity_from_cursor = 0,
-- 			particle_random_velocity = 300,
-- 			particle_damping = 0.1,
-- 			particle_gravity = 50,
-- 		})
-- 	end,
-- }
